name: JBossWS-CXF CI Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ['11']
        profile: ['']
    steps:
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.4
        with:
          oc version: 'v3.11.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the cluster
        run: oc cluster status
      - name: Checkout jbossws-cxf
        uses: actions/checkout@v2
      - name: Checkout wildfly
        uses: actions/checkout@v2
        with:
          repository: wildfly/wildfly
          path: './wildfly'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Build docbook
        run: mvn -s ./.m2-settings.xml -f docbook/pom.xml install
      - name: Build with Maven Java ${{ matrix.java }} ${{ matrix.profile }}
        run: |
          mvn -s ./.m2-settings.xml -fae ${{ matrix.profile }} clean install
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '${{ github.workspace }}/**/surefire-reports/*.*'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '${{ github.workspace }}/**/*.log'